version: '3.2'

services:
  eosnode:
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_eosnode
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-eosnode
    volumes:
      - eosio:/opt/eosio
    logging:
      options:
        max-size: "50m"
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m
    networks:
      - scrapers-network

  eos:
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_eos
    depends_on:
      - eosnode
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/build/Dockerfile-eos
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/diadata/secrets/api_diadata.json

volumes: 
  eosio:
    external: true

networks: 
  scrapers-network:
